
version: '3'

services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432
    volumes:
    - ./data/contacts_dev:/contacts_dev
    environment:
      POSTGRES_USER: contacts_dev
      POSTGRES_PASSWORD: contacts_dev_pass
      POSTGRES_DB: contacts_dev
      PGDATA: /contacts_dev


  redis:
    image: redis:4.0.11-alpine
    ports:
    - 6379:6379

  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_MASTER_URL: postgres://contacts_dev:contacts_dev_pass@db/contacts_dev
      REDIS_HOST: redis